export const ENDPOINTS = {
  AUTH: '/auth/login/staff',
  CUSTOMERS: '/customers',
  CUSTOMERS_SEARCH: '/customers/identification',
  CUSTOMERS_SUBTYPES: '/customers/subtypes',
  ACCOUNTS: '/accounts',
  ACCOUNTS_ACTIVATE: '/accounts/:accountNumber/activate',
  ACCOUNTS_INACTIVATE: '/accounts/:accountNumber/inactivate',
  ACCOUNTS_BLOCK: '/accounts/:accountNumber/block',
  ACCOUNTS_SUSPEND: '/accounts/:accountNumber/suspend',
  TRANSACTIONS: '/transactions',
  TRANSACTIONS_DEBITS: '/transactions/debits',
  TRANSACTIONS_CREDITS: '/transactions/credits',
  TRANSACTIONS_TRANSFERS: '/transactions/transfers',
  TRANSACTIONS_HISTORY: '/transactions/history',
  BRANCHES: '/branches',
  HOLIDAYS: '/holidays',
  HOLIDAYS_BUSINESS_DAY: '/holidays/business-day',
  NOTIFICATIONS: '/notifications'
};
